import {types} from 'ref';
import * as ref from 'ref';

export default {
  void:        types.void,
  int8:        types.int8,
  uint8:       types.uint8,
  int16:       types.int16,
  uint16:      types.uint16,
  int32:       types.int32,
  uint32:      types.uint32,
  int64:       types.int64,
  uint64:      types.uint64,
  float:       types.float,
  double:      types.double,
  CString:     types.CString,
  bool:        types.bool,
  byte:        types.byte,
  char:        types.char,
  uchar:       types.uchar,
  short:       types.short,
  ushort:      types.ushort,
  int:         types.int,
  uint:        types.uint,
  long:        types.long,
  ulong:       types.ulong,
  longlong:    types.longlong,
  ulonglong:   types.ulonglong,
  sizet:       types.size_t,
  void_p:      ref.refType(types.void),
  int8_p:      ref.refType(types.int8),
  uint8_p:     ref.refType(types.uint8),
  int16_p:     ref.refType(types.int16),
  uint16_p:    ref.refType(types.uint16),
  int32_p:     ref.refType(types.int32),
  uint32_p:    ref.refType(types.uint32),
  int64_p:     ref.refType(types.int64),
  uint64_p:    ref.refType(types.uint64),
  float_p:     ref.refType(types.float),
  double_p:    ref.refType(types.double),
  CString_p:   ref.refType(types.CString),
  bool_p:      ref.refType(types.bool),
  byte_p:      ref.refType(types.byte),
  char_p:      ref.refType(types.char),
  uchar_p:     ref.refType(types.uchar),
  short_p:     ref.refType(types.short),
  ushort_p:    ref.refType(types.ushort),
  int_p:       ref.refType(types.int),
  uint_p:      ref.refType(types.uint),
  long_p:      ref.refType(types.long),
  ulong_p:     ref.refType(types.ulong),
  longlong_p:  ref.refType(types.longlong),
  ulonglong_p: ref.refType(types.ulonglong),
  sizet_p:     ref.refType(types.size_t)
}
